spring.application.name=ChatApp
server.port=8080
cors.allowed.origins=http://localhost:5173

aws.region=${AWS_REGION:us-east-1}
aws.s3.bucket-name=${S3_BUCKET_NAME:lista7-chat-images}
aws.dynamodb.table-name=${DYNAMODB_TABLE_NAME:lista7-chat-history}
aws.dynamodb.live-chat-table-name=${LIVE_CHAT_TABLE_NAME:lista7-live-chat}
